#!/bin/bash
#
# np (short for neuropipe) sets up the scaffolding for a new project.
# Copyright (C) 2010 mason simon (mgsimon@princeton.edu)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


#### shell options ####
set -e   # fail immediately on error


#### constants ####
EXIT_IMPROPER_USAGE=1
EXIT_PROJ_EXISTS=2
PROJECT_TEMPLATE=project-template
NP_DIR=$(dirname $0)


#### main ####
if [ $# -ne 1 ]; then
  echo "usage: $(basename $0) PROJECT_NAME"
  exit $EXIT_IMPROPER_USAGE
fi

proj=$1

if [ -e $proj ]; then
  echo "$proj dir already exists. if you'd like to overwrite, delete it and try again"
  exit $EXIT_PROJ_EXISTS
fi

cp --recursive $NP_DIR/$PROJECT_TEMPLATE $proj
echo "created project '$proj' with the following structure:"
echo "  $proj"
cat $NP_DIR/dir-structure.txt
